version: '39'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: barbershop
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: tony
        ports:
            - "5432:5432"
